### ISSUE TITLE
XCUITEST Driver suddenly stops during automation run

### ISSUE THREAD

**Issue by erdncyz** [appium/appium-xcuitest-driver#2453] opened 2024-08-15 08:12 UTC
While running, appium suddenly stops and does not print any errors. When I examine it, it seems to suddenly stop while searching for the locater.

Appium 2.11.3
Appium plugin list 9.2.1
Xcuitest 7.24.15

My gist : https://gist.github.com/erdncyz/56a1ac4c4b170f7c9979710f493f2373

![image](https://github.com/user-attachments/assets/575be074-eb0a-44a4-8908-7039cb78a9cd)

**Comment by KazuCocoa** [comment] 2024-08-15 09:40
Duplicate of https://github.com/appium/appium/issues/20456

**Closed by KazuCocoa** 2024-08-15 09:40 UTC
