### ISSUE TITLE
keep loading in inspector due to "stale element reference"

### ISSUE THREAD

**Issue by pppppino** [appium/appium-xcuitest-driver#2486] opened 2024-10-30 07:07 UTC
When I start "Appium inspector", The page_source and Screenshot are always loading. After checking log, I found a 404 error, please help to check, thanks

![Screenshot2024_10_30_150427](https://github.com/user-attachments/assets/174839ae-d99e-4dab-8b20-1304a3e82250)

log:

`[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Proxying [GET /screenshot] to [GET http://127.0.0.1:8300/session/0566854F-B966-437D-B8D7-E759B9F483C3/screenshot] with no body
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEZaADAAQAAAABAAAJhAAAAACsblQTAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAA7KucRbQXQAAQABJREFUeAHsvXeUFMe27vn+mXlz16z7Zt6bNzPrvnn3niOgve+uLu/bV3va0AZvhZXBSwIhjGg4cnjkHQJJ5+hICCOBEEZ475FAeO+9b+icLzKqiuruaodt89UKlbKyoiIjf7mz2V/uiB3/SW/IYCEBEiABEiABEiABEiABEiABEqhO4D9V38U9JEACJEACJEACJEACJEACJEACIEC9xPAaCZAACZAACZAACZAACZAACfgnQL3knwvFNAmQAAmQAAmQAAmQAAmQAAlQL1EvkQAJkAAJkAAJkAAJkAAJkIB/AtRL/rlQSZMACZAACZAACZAACZAACZAA9RL1EgmQAAmQAAmQAAmQAAmQAAn4J0C95J8LlTQJkAAJkAAJkAAJkAAJkAAJUC9RL5EACZAACZAACZAACZAACZCAfwLUS/65UEmTAAmQAAmQAAmQAAmQAAmQAPUS9RIJkAAJkAAJkAAJkAAJkAAJ+CdAveSfC5U0CZAACZAACZAACZAACZAACVAvUS+RAAmQAAmQAAmQAAmQAAmQgH8C1Ev+uVBJkwAJkAAJkAAJkAAJkAAJkAD1EvUSCZAACZAACZAACZAACZAACfgnQL3knwuVNAmQAAmQAAmQAAmQAAmQAAlQL1EvkQAJkAAJkAAJkAAJkAAJkIB/AtRL/rlQSZMACZAACZAACZAACZAACZAA9RL1EgmQAAmQAAmQAAmQAAmQAAn4J0C95J8LlTQJkAAJkAAJkAAJkAAJkAAJUC9RL5EACZAACZAACZAACZAACZCAfwL...
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEZaADAAQAAAABAAAJhAAAAACsblQTAAAAHGlET1QAAAACAAAAAAAABMIAAAAoAAAEwgAABMIAA7KucRbQXQAAQABJREFUeAHsvXeUFMe27vn+mXlz16z7Zt6bNzPrvnn3niOgve+uLu/bV3va0AZvhZXBSwIhjGg4cnjkHQJJ5+hICCOBEEZ475FAeO+9b+icLzKqiuruaodt89UKlbKyoiIjf7mz2V/uiB3/SW/IYCEBEiABEiABEiABEiABEiABEqhO4D9V38U9JEACJEACJEACJEACJEACJEACIEC9xPAaCZAACZAACZAACZAACZAACfgnQL3knwvFNAmQAAmQAAmQAAmQAAmQAAlQL1EvkQAJkAAJkAAJkAAJkAAJkIB/AtRL/rlQSZMACZAACZAACZAACZAACZAA9RL1EgmQAAmQAAmQAAmQAAmQAAn4J0C95J8LlTQJkAAJkAAJkAAJkAAJkAAJUC9RL5EACZAACZAACZAACZAACZCAfwLUS/65UEmTAAmQAAmQAAmQAAmQAAmQAPUS9RIJkAAJkAAJkAAJkAAJkAAJ+CdAveSfC5U0CZAACZAACZAACZAACZAACVAvUS+RAAmQAAmQAAmQAAmQAAmQgH8C1Ev+uVBJkwAJkAAJkAAJkAAJkAAJkAD1EvUSCZAACZAACZAACZAACZAACfgnQL3knwuVNAmQAAmQAAmQAAmQAAmQAAlQL1EvkQAJkAAJkAAJkAAJkAAJkIB/AtRL/rlQSZMACZAACZAACZAACZAACZAA9RL1EgmQAAmQAAmQAAmQAAmQAAn4J0C95J8LlTQJkAAJkAAJkAAJkAAJkAAJUC9RL5EACZAACZAACZAACZAACZCAfwLUS/65UEmT...
[38;5;0m[HTTP][0m [37m<-- GET /session/515e1db0-bb41-4ed3-b48a-78fca29591e4/screenshot [39m[32m200[39m [90m225 ms - 416068[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mGET[39m [37m/session/515e1db0-bb41-4ed3-b48a-78fca29591e4/window/rect[39m
[38;5;0m[HTTP][0m [90m{}[39m
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Calling AppiumDriver.getWindowRect() with args: ["515e1db0-bb41-4ed3-b48a-78fca29591e4"]
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Executing command 'getWindowRect'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Proxying [GET /window/size] to [GET http://127.0.0.1:8300/session/0566854F-B966-437D-B8D7-E759B9F483C3/window/size] with no body
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Parsed BUILD_DIR configuration value: '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-hkxolhdthpdnijfifbqskszoaijk/Build/Products'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Got derived data root: '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-hkxolhdthpdnijfifbqskszoaijk'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'us.zoom.videomeetings.inhouse'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound","traceback":"(\n\t0  CoreFoundation 0x000000018140fd30 55A96CFE-3141-3F56-8AB1-569C607B9370 + 601392\n\t1  libobjc.A.dylib  0x0000000198c2fee4 objc_exception_throw + 56\n\t2  WebDriverAgentLib  0x0000000104919030 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 800\n\t3  WebDriverAgentLib  0x0000000104910060 -[XCUIElement(WebDriverAttributesForwarding) fb_snapshotForAttributeName:] + 736\n\t4  WebDriverAgentLib  0x0000000104910298 -[XCUIElement(WebDriverAttributesForwarding) forwardingTargetForSelector:] + 220\n\t5  CoreFoundation 0x00000001813a913c 55A96CFE-3141-3F56-8AB1-569C607B9370 + 180540\n\t6  Co...
[38;5;112m[W3C][0m Matched W3C error code 'stale element reference' to StaleElementReferenceError
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Encountered internal error running command: StaleElementReferenceError: The previously found element "Application 'us.zoom.videomeetings.inhouse'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at errorFromW3CJsonCode (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at ProxyRequestError.getActualError (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at JWProxy.command (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at processTicksAndRejections (node:internal/process/task_queues:95:5)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.proxyCommand (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.getWindowSizeNative (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:277:12)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.getWindowSize (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:52:14)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.getWindowRect (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:121:29)
[38;5;0m[HTTP][0m [37m<-- GET /session/515e1db0-bb41-4ed3-b48a-78fca29591e4/window/rect [39m[33m404[39m [90m2153 ms - 1634[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mGET[39m [37m/session/515e1db0-bb41-4ed3-b48a-78fca29591e4/source[39m
[38;5;0m[HTTP][0m [90m{}[39m
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Calling AppiumDriver.getPageSource() with args: ["515e1db0-bb41-4ed3-b48a-78fca29591e4"]
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Executing command 'getPageSource'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8300/session/0566854F-B966-437D-B8D7-E759B9F483C3/source?format=xml&scope=AppiumAUT] with no body
[38;5;0m[HTTP][0m [37m-->[39m [37mGET[39m [37m/session/515e1db0-bb41-4ed3-b48a-78fca29591e4/timeouts[39m
[38;5;0m[HTTP][0m [90m{}[39m
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Calling AppiumDriver.getTimeouts() with args: ["515e1db0-bb41-4ed3-b48a-78fca29591e4"]
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Executing command 'getTimeouts'
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'us.zoom.videomeetings.inhouse'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound","traceback":"(\n\t0  CoreFoundation 0x000000018140fd30 55A96CFE-3141-3F56-8AB1-569C607B9370 + 601392\n\t1  libobjc.A.dylib  0x0000000198c2fee4 objc_exception_throw + 56\n\t2  WebDriverAgentLib  0x0000000104919030 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 800\n\t3  WebDriverAgentLib  0x0000000104919274 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes:maxDepth:] + 152\n\t4  WebDriverAgentLib  0x00000001048d0ba4 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 720\n\t5  WebDriverAgentLib  0x00000001048d030c +[FBXPath xmlRepresentationWithRootElement:writer:elemen...
[38;5;112m[W3C][0m Matched W3C error code 'stale element reference' to StaleElementReferenceError
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Encountered internal error running command: StaleElementReferenceError: The previously found element "Application 'us.zoom.videomeetings.inhouse'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at errorFromW3CJsonCode (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at ProxyRequestError.getActualError (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at JWProxy.command (/Users/admin/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at processTicksAndRejections (node:internal/process/task_queues:95:5)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.proxyCommand (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.mobileGetSource (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m  at XCUITestDriver.getPageSource (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
[38;5;0m[HTTP][0m [37m<-- GET /session/515e1db0-bb41-4ed3-b48a-78fca29591e4/source [39m[33m404[39m [90m2130 ms - 1499[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;32m[XCUITestDriver@ccd0 (515e1db0)][0m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}`

**Comment by pppppino** [comment] 2024-10-30 07:10
It works when I restart my app...

**Comment by eglitise** [comment] 2024-10-31 09:34
Likely duplicate of https://github.com/appium/appium/issues/19566. Please refer to the discussion there.

**Closed by eglitise** 2024-10-31 09:34 UTC
