### ISSUE TITLE
Unable to interact with the iOS permission prompt after updating from v5.14.0 to v5.14.1 or later

### ISSUE THREAD

**Issue by rolandmoldovan** [appium/appium-xcuitest-driver#2311] opened 2024-01-31 07:11 UTC
I've noticed that after updating appium-xcuitest-driver from v5.14.0 to v5.14.1(or later), I'm no longer able to accept or decline any OS permission prompt in my E2E tests. Has there been any change in this regard?

Appium: 2.4.1.
Xcuitest: 5.14.1 (all good with 5.14.0)

**Comment by KazuCocoa** [comment] 2024-01-31 09:07
Possible duplicate of https://github.com/appium/appium/issues/19716 ?

**Comment by KazuCocoa** [comment] 2024-01-31 23:05
Please use `5.15.1`, it should work as same as `v5.14.0`. The change will come in a future release

**Closed by KazuCocoa** 2024-01-31 23:05 UTC

**Comment by rolandmoldovan** [comment] 2024-02-01 11:59
Thank you! Indeed, versions 5.15.1 (up to to 5.16.1) is working as expected. However, it seems that the issue has resurfaced in the next major version (6.0.0) despite mentioning the inclusion of WDA ^6.0.0, which is expected to have fixes for active application detection.

**Comment by outi5** [comment] 2024-02-05 16:08
@KazuCocoa, I'm noticing the same issue as @rolandmoldovan reported on 6.0.1. There seems to be a reintroduction of the issue corrected in 5.15.1.

**Comment by KazuCocoa** [comment] 2024-02-05 16:15
It is expected as a breaking change in https://github.com/appium/appium-xcuitest-driver/blob/master/CHANGELOG.md#600-2024-02-01
We just moved the fix and change from minor/patch version to major version update

**Comment by HarshdeepSingh3009** [comment] 2024-03-13 15:16
I am seeing the same issue with Appium 2.5.1  and xcuitest@7.3.0. What previous version contains the fix for this ? I will take that  till it get fixed in one of the latest releases.

**Comment by RenilAneesh123** [comment] 2024-03-14 14:01
@KazuCocoa  facing the same issue even after upgrading to 7.3. when can we expect this to be resolved?

**Comment by rolandmoldovan** [comment] 2024-03-14 14:31
@HarshdeepSingh3009 the last version that worked for me is xcuitest@5.16.1, after that version, looks like after xcuitest@6.0.0 there were some changes which I did not figure out (yet had the time to do) how to implement, read the changelog: https://github.com/appium/appium-xcuitest-driver/blob/master/CHANGELOG.md#600-2024-02-01

**Comment by KazuCocoa** [comment] 2024-03-14 19:11
https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard would also help for the latest version

**Comment by HarshdeepSingh3009** [comment] 2024-03-14 19:33
@rolandmoldovan and @KazuCocoa  .. thank you for the response. For now, I have rolled back to v5.15.1. I will try and implement one of the approaches, mentioned in the above link.
